# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_used', models.CharField(max_length=1000, null=True)),
                ('current_pot', models.IntegerField(null=True)),
                ('big_blind', models.IntegerField(null=True)),
                ('small_blind', models.IntegerField(null=True)),
                ('ante', models.IntegerField(null=True)),
                ('number_of_players', models.IntegerField(null=True)),
                ('players_turn', models.IntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('cards_on_board', models.CharField(max_length=1000)),
                ('phase_of_hand', models.PositiveIntegerField(null=True)),
                ('last_bet_size', models.PositiveIntegerField(null=True)),
                ('bet_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.PositiveIntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('loses', models.IntegerField(null=True)),
                ('hole_cards', models.CharField(max_length=1000)),
                ('number', models.PositiveIntegerField()),
                ('current_bet_size', models.PositiveIntegerField(null=True)),
                ('current_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
            ],
        ),
    ]
